name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Be explicit with strings to avoid accidental YAML number parsing (e.g. `3.1` -> 3.1)
        python-version: [ '3.10' ]
        node-version: [ '20' ]

    steps:
      - uses: actions/checkout@v4

      - name: Debug matrix
        run: |
          echo "Matrix python-version = '${{ matrix.python-version }}'"
          echo "Runner OS = $RUNNER_OS"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # Use an explicit patch/minor version or major+minor (e.g. '3.10' or '3.10.x')
          python-version: ${{ matrix.python-version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        run: |
          pytest -q

      - name: Run JS tests
        run: |
          npm ci --no-audit --no-fund || true
          node --version
          npm run test:js
